### ISSUE TITLE
Here are some GP's work sheets to go through ...

### ISSUE THREAD

**Issue by grd349** [ni-phy/year4-project#1]
@asf1418 @ni-phy 

In this Github repo https://github.com/grd349/EDAS2018_Davies 

You'll find some of my GP resources. 

Can I encourage you to try and work your way through the kernel sandbox .ipynb file and see if you can get things working! 

should if you have questions ...

**Comment by asf1418** [comment]
Hey @grd349,
Found the kernel sandbox really interesting. Im now looking at ScratchGP.ipynb. I am having some trouble with the predict function. I am not sure whether I should be using the np.dot or built in multiplication methods. 

When I have tried the dot product method, this has failed as A, B and C are all different shapes. 

When using the built in multiplication (A*B etc.) the shapes of y_pred and sigma new are different (attached is my implementation using this method).
![mulit method](https://user-images.githubusercontent.com/15049283/95767495-bd040e80-0cac-11eb-9ee0-447de61e9dad.PNG)

**Comment by grd349** [comment]
>      y_pred = np.dot(B, Ainv).dot(y_1)
>      sigma_new = C - np.dot(B, Ainv).dot(B.T)
>      return y_pred, sigma_new.diagonal()

The dot product is your friend here :)

**Comment by grd349** [comment]
> Ainv = np.linalg.inv(A)

Numpy for the matrix inversion might help with the numerical stability.

**Comment by asf1418** [comment]
![dot method](https://user-images.githubusercontent.com/15049283/95768474-4ec04b80-0cae-11eb-817f-027cb0f35788.PNG)
![dot error](https://user-images.githubusercontent.com/15049283/95768479-5122a580-0cae-11eb-90e9-b4186a48725b.PNG)

Hmm, when I try a method like that I get the following error

**Comment by asf1418** [comment]
I am using the numpy inv method in that example (imported the method explictly)

**Comment by grd349** [comment]
> B = kernel(t_1, t_2, p).T
    C = kernel(t_2, t_2, p)
    A = kernel(t_1, t_1, p)

I do this ...

**Comment by asf1418** [comment]
Thnaks, that seems to have fixed it! Why are we using the transpose of B here?

**Comment by grd349** [comment]
Good question - it's just about keeping track of the shapes of the covariance matrices.
