### ISSUE TITLE
Residual plot

### ISSUE THREAD

**Issue by asf1418** [ni-phy/year4-project#3]
Hey @grd349,

I have got a nice plot for my graph of predicted values against data values, but my residual histogram plot doesnt look quite like expected.
![residual](https://user-images.githubusercontent.com/15049283/97504359-9dd4d480-196e-11eb-9424-6fa19fc6e41f.PNG)
![Pred_vs_data](https://user-images.githubusercontent.com/15049283/97504364-a0372e80-196e-11eb-8175-21f12c2839fb.PNG)
Can you think of why my residual plot is so sharp?

**Comment by asf1418** [comment]
Forgot to say, but for the data here I used sampling.

**Comment by grd349** [comment]
> Can you think of why my residual plot is so sharp?

Good spot and excellent question.  Good that you are challenging your own results. 

My suggestion is that the uncertainties are too large given the residual values.  This might be happening for a few reasons.

1. ). It could be the GP kernel form it not quiet correct for the task. 
2. ) It could be a problem with the way the PyMC3 implementation of the GP is adding (or not) noise to the predictions
3. ) It could be something else entirely.

Start with 2.  Can you see anything in the PyMC3 docs that discusses including the noise on the uncertainties but not on the mean predictions (it would be odd if it did but ...)

**Comment by asf1418** [comment]
Hey @grd349 , Ive messed about with my code and made the residual plot less sharp when sampling (I was adding noise to the predictions). But it still doesnt quite fit the N(0,1) shape.
![Z - residual plot 2](https://user-images.githubusercontent.com/15049283/97879950-7b4d0d80-1d18-11eb-9ff8-fb2bc2d7b859.PNG)
![pred vs data 2](https://user-images.githubusercontent.com/15049283/97879956-7c7e3a80-1d18-11eb-8b71-a3837ad47c5b.PNG)
Also, it appears that for higher values the prediction vs data plot strays from the y=x line.

Would this suggest that the kernel is not properly suited for the task? For reference I am using two squared exp kernels (summing or multiplying the two doesnt make too much difference).

In regards to point 2:
When constructing the GP likelihood, you are required to use a noise parameter
 "obs = gp.marginal_likelihood("obs", X=Xs, y=y, noise=sigman)"
When noise=0, no noise is made (even if I set pred_noise in predict to True).

Up till now I have been gathering my noise values from HalfCauchu(beta=3, and this is typically around mean=1.2).


When I use find_map (with the Half cauchy noise values and pred_noise =True), the height of the residual plot is far closer to what I hope it would be, but is offset from the center 
![map res](https://user-images.githubusercontent.com/15049283/97881996-00d1bd00-1d1b-11eb-899e-00df110563c2.PNG)
![map pvd](https://user-images.githubusercontent.com/15049283/97882001-03341700-1d1b-11eb-9ddc-e4a6f0b617d7.PNG)

Also the error bars on the pred vs data plot are very small.

Any ideas on where to go from here?

**Comment by asf1418** [comment]
![params](https://user-images.githubusercontent.com/15049283/98120986-95b4f180-1ea6-11eb-8109-3b653ef4e0a0.PNG)
